name: DotGov Scan

on:
  schedule:
    - cron: '0 6 * * *'
  issues:
      types:
        - opened

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        # Pass GitHub token to authenticate the push
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Create Report Directory
      run: mkdir -p ./reports
    
    - name: Install Playwright Browser
      run: playwright install --with-deps chromium
    
    - name: Run main.py
      run: |
        python main.py
    - name: Commit new reports directory
      run: |
        git config --local user.name "deepwaterpaladin"
        git config --local user.email "rielly.young11@gmail.com"
        git add reports/*
        git commit -m "Add new reports directory from pipeline run"
        git push
      
