# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: DotGov Scan

on:
  issues:
      types:
        - opened
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Create Report Directory
      run: mkdir -p ./reports
    
    - name: Install Playwright Browser
      run: playwright install --with-deps chromium
    
    - name: Run main.py
      run: |
        playwright install
        python main.py
    - name: Commit new reports directory
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add reports/*
        git add recordings/*
        git commit -m "Add new reports directory from pipeline run"
        git push
      env:
        # Pass GitHub token to authenticate the push
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
